language: minimal
deploy:
  provider: s3
  access_key_id: AKIAVAENIR56NNR55NVD
  secret_access_key:
    secure: AC2Pab4t4dpdM1JIyzpZXiKXLdKu+WeHtdTmuI433c8oDp7ghuSsUylH/45OWUfRT0bruZljBDH7cFGbXuECcDSs1XFCZQKaJIAlQQmzzC6heHG6ixm5wECbJoSd3Woo1DPORgFw8eQc6ymWa2WO6yrr3/V/ErpuEbASGqsaW3816t9iQGGyFFL8kgQ6f7KLNROfrRPvigFTUJgp+jLktB7k7ZVpIRPagEA/bAqiq6AfOExVwt456uInkEuR8Wj5miBtI5lBxe6TJF4Pkm13OhKT4wso6ePP6D5Hw+vzZyNPIHY5A+8K0j/zsSEgJqkw4MEyzEhCaiRs7ZLyfkSQIFBVX5Bq+ggTb3ISTqSUOkjZ1lrzf7l5vpI12wFt2QyJdQcp86CAOABEerPowFYyIGUUwdJVJIDtdDZoA5K6IVw1z1aKckYxJ3UwAL9jnLboiE/lTwr+lCevE700Xo/sk3AFiRyrYhZWsOB8S8voZQLRlbB+EUoUvDBlbCEzBl+aJqKGsL2ePaPJabCa/xcEWlT6iVR61qYbImZUJN+xRpevGEwMVOWFURMMxKC7G79vIZF8F8ri9icFt7dwU2eLYtd1Yx4uMM8Dr5Yftnk3xjpsyxgHrrnuUnWa30BMU5PjeizRi3wFoPhXruJeS9cSaHQLz54I5vzlav+8/kNEN/c=
  bucket: timstwitterlisteningparty.com
  skip_cleanup: true
  region: eu-west-2
